---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "numbergenerator-viewer-service"
  namespace: "numbergenerator"
  labels:
    app: "numbergenerator"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "numbergenerator-viewer"
  type: "LoadBalancer"
  loadBalancerIP: ""
