---
apiVersion: v1
kind: ConfigMap
metadata:
  name: numbergenerator-platform-cm
  namespace: numbergenerator
  labels:
    app: numbergenerator
data:
  application.yml: |-
    spring:
      kafka:
        producer:
            bootstrap-servers: kafka-cluster-kafka-bootstrap:9092
            #key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.LongSerializer
