---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: numbergenerator 
  name: numbergenerator-viewer
  namespace: numbergenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: numbergenerator-viewer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: numbergenerator-viewer
    spec:
      containers:
      - image: docker.io/ccangemi/numbergenerator-viewer:v2
        imagePullPolicy: Always
        name: numbergenerator-viewer
        resources: {}
        volumeMounts:
          - name: numbergenerator-viewer-cm 
            mountPath: "/app/application.yml"
            subPath: application.yml
            readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: numbergenerator-viewer-cm
        configMap:
          name: numbergenerator-viewer-cm 
          items:
          - key: application.yml 
            path: application.yml