server:
  port: 9080

numberGenerator:
  rest:
    endpoint: ${NG_REST_ENDPOINT:http://localhost:8080/random}

spring:
  kafka:
    consumer:
      bootstrap-servers: kafka-cluster-kafka-bootstrap:9092
      group-id: test-consumer
      auto-offset-reset: earliest
      #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration