---
apiVersion: v1
kind: ConfigMap
metadata:
  name: numbergenerator-viewer-cm
  namespace: numbergenerator
  labels:
    app: numbergenerator
data:
  application.yml: |-
    server:
      port: 8080
    numberGenerator:
      rest:
        endpoint: "http://numbergenerator-platform-service:8080/random"